version: "3.8"

services:
  api:
    container_name: sailor-api
    image: discusss/sailor:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://sailor:sailor@sailor-postgres:5432/sailor
      PROMETHEUS_KEY: ${PROMETHEUS_KEY}
      MASTER_KEY: ${MASTER_KEY}
      WEBHOOK_URL: http://webhook:5001
      WEBHOOK_HASH_KEY: ${WEBHOOK_HASH_KEY}
      ROCKET_ENV: prod
      ROCKET_ADDRESS: 0.0.0.0
    depends_on:
      postgres:
        condition: service_healthy

  webhook:
    container_name: webhook
    image: discusss/sailor-webhook-server:latest
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      REVIEWING_CHANNEL_ID: ${REVIEWING_CHANNEL_ID}
      WEBHOOK_HASH_KEY: ${WEBHOOK_HASH_KEY}

  bot:
    container_name: sailor-bot
    image: discusss/sailor-bot:latest
    restart: unless-stopped
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      API_BASE_URL: http://sailor-api:8000
      API_AUTH_KEY: ${MASTER_KEY}
      WEBHOOK_HASH_KEY: ${WEBHOOK_HASH_KEY}
      PYTHONPATH: /bot

  postgres:
    container_name: sailor-postgres
    image: postgres:15.2-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U sailor -h localhost
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_USER: sailor
      POSTGRES_PASSWORD: sailor
      PGPASSWORD: sailor
      PGPORT: 5432
      POSTGRES_PORT: 5432
      POSTGRES_DB: sailor
      PGDATABASE: sailor
    volumes:
      - ./postgres:/var/lib/postgresql/data
